#!/usr/bin/env node

// generate_section_summary_pm.js
// Converts sectionSummary.js into SectionSummary.pm for use in Perl

const fs = require('fs');
const path = require('path');
const { sectionSummary } = require('../shared/constants');

const outputPath = path.join(__dirname, '../perl-lib/SectionSummary.generated.pm');

function escapePerlString(str) {
    return str.replace(/'/g, "\\'");
}

function toPerlArray(arr) {
    return "[ " + arr.map(s => `'${escapePerlString(s)}'`).join(", ") + " ]";
}

function toPerlHashArray(arr) {
    return "[\n" + arr.map(section => {
        const name = escapePerlString(section.name);
        const sections = toPerlArray(section.sections);
        return `    { name => '${name}', sections => ${sections} }`;
    }).join(",\n") + "\n]";
}

const perlContent = `package SectionSummary;

#
# This file is generated by src/admin/generate_section_summary.js
# DO NOT EDIT BY HAND, IT WILL BE OVERWRITTEN !!!
#

use strict;
use warnings;
use Exporter 'import';
our @EXPORT_OK = qw(getSectionSummary);

sub getSectionSummary {
    return ${toPerlHashArray(sectionSummary)};
}

1;
`;

fs.writeFileSync(outputPath, perlContent);
console.log(`✅ SectionSummary.pm generated at: ${outputPath}`);

