package SectionSummary;

#
# This file is generated by src/admin/generate_section_summary.js
# DO NOT EDIT BY HAND, IT WILL BE OVERWRITTEN !!!
#

use strict;
use warnings;
use Exporter 'import';
our @EXPORT_OK = qw(getSectionSummary);

sub getSectionSummary {
    return [
    { name => 'Native Coins', sections => [ 'BNB', 'ETH', 'POL', 'VTRU', 'SOL', 'TEZ' ] },
    { name => 'VTRU Bridged', sections => [ 'VTRU on BSC', 'VTRU on ETH' ] },
    { name => 'USDC', sections => [ 'USDC on VTRU(USDC.pol)', 'USDC on ETH', 'USDC on BSC', 'USDC on POL' ] },
    { name => 'Staked', sections => [ 'VTRU Staked', 'SEVO-X Staked' ] },
    { name => 'Vitruveo Coins & Tokens', sections => [ 'VERSE', 'VIBE', 'VORTEX', 'VTRO', 'VUSD', 'wVTRU' ] },
    { name => 'Sabong', sections => [ 'SEVO', 'SEVO-X' ] },
    { name => 'Vitruveo Exchange', sections => [ 'V3DEX', 'VITDEX' ] }
];
}

1;
