package SectionSummary;

#
# This file is generated by src/admin/generate_section_summary.js
# DO NOT EDIT BY HAND, IT WILL BE OVERWRITTEN !!!
#

use strict;
use warnings;
use Exporter 'import';
our @EXPORT_OK = qw(getSectionSummary);

sub getSectionSummary {
    return [
    { name => 'Native Coins', sections => [ 'VTRU', 'ETH', 'AVAX', 'BNB', 'POL', 'SOL', 'TEZ' ] },
    { name => 'ETH Bridged', sections => [ 'ETH on Arbitrum', 'ETH on Optimism', 'ETH on Base' ] },
    { name => 'VTRU Bridged', sections => [ 'VTRU on ETH', 'VTRU on BSC' ] },
    { name => 'USDC', sections => [ 'USDC on VTRU(USDC.pol)', 'USDC on Ethereum', 'USDC on BNB Chain', 'USDC on Polygon', 'USDC on Solana', 'USDC on Arbitrum', 'USDC on Optimism', 'USDC on Base', 'USDC on Avalanche' ] },
    { name => 'USDT', sections => [ 'USDT on Ethereum', 'USDT on Polygon', 'USDT on Arbitrum', 'USDT on Optimism', 'USDT on Avalanche' ] },
    { name => 'Staked', sections => [ 'VTRU Staked', 'SEVO-X Staked' ] },
    { name => 'Vitruveo Coins & Tokens', sections => [ 'VERSE', 'VIBE', 'VORTEX', 'VTRO', 'VUSD', 'wVTRU' ] },
    { name => 'Sabong', sections => [ 'SEVO', 'SEVO-X' ] },
    { name => 'Vitruveo Exchange', sections => [ 'V3DEX', 'VITDEX' ] }
];
}

1;
